config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Settings.Sidekiq.username && password == Settings.Sidekiq.password
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  get 'welcome/index'

  root 'item_tasks#index'

  get 'index', to: redirect('welcome/index')

  get 'login' => 'welcome#login'
  post 'login' => 'welcome#create'

  get 'logout' => 'welcome#destroy'

  get 'logs' => 'trace_logs#index'

  get "fetch_product_feed" => "smart_ads/board#fetch_product_feed"

  namespace :users do
    resources :subscriptions, only: [:index, :new, :create, :edit, :update]
    resources :reviews do
      collection do
        get 'ajax', action: :review_ajax
      end
    end
    resources :review_reports do
      member do
        get 'create_zendesk_ticket', action: :create_zendesk_ticket
      end
      collection do
        get 'ajax', action: :review_report_ajax
      end
    end
  end
  resources :users, only: [:index, :show] do
    collection do
      post 'disable'
      post 'weight', action: :update_weight
      post 'risk', action: :user_risk

      get 'map'
      get 'disabled_state', action: :index_disabled_users
      get 'risk_state', action: :index_risk_users
      get 'bad_state', action: :index_bad_users

      get 'ajax', action: :user_ajax
    end

    member do
      post 'weight', action: :update_weight
      get 'portrait'
      post 'email'
    end

  end

  resources :products, only: [:index, :show] do
    collection do
      get 'hot_items', action: :index_hot_items
      get 'weight', action: :index_weight
      post 'weight', action: :update_weight
      put 'weight', action: :update_weight
      post 'categories', action: :update_categories
      post 'categories_new', action: :update_categories_new
      put 'approve'

      get 'map'
      get 'ajax', action: :product_ajax
    end

    member do
      get 'images'
      post 'categories', action: :update_categories
      get 'offers', action: :offers
      post 'weight', action: :update_weight
    end

    resource :state, controller: 'product_states', only: [:create] do
    end
  end

  resources :product_reports, only: [:index] do
    member do
      get 'feedback', action: :edit
      post 'feedback', action: :update
      get 'create_zendesk_ticket', action: :create_zendesk_ticket
    end
  end

  resources :user_reports, only: [:index] do
    member do
      get 'feedback', action: :edit
      post 'feedback', action: :update
      get 'create_zendesk_ticket', action: :create_zendesk_ticket
    end
  end

  resources :categories, as: 'category', except: [:destroy] do
    collection do
      get 'treeview'
    end

    member do
      get 'publish', action: :publish_category
      get 'draft', action: :draft_category
      get 'disable', action: :disable_category
      get 'enable', action: :enable_category
    end
  end

  resources :admins, only: [:index, :new, :create, :destroy, :edit, :show, :update] do
    resource :super_state, controller: 'admin_super_states', only: [:create, :destroy]
    member do
      get 'password', action: :password_edit
      post 'password', action: :password_update
    end
    collection do
      resources :schedules, controller: 'operator_schedules'
      get 'item_risk_keywords', action: :edit_item_risk_keywords
      post 'item_risk_keywords', action: :update_item_risk_keywords
      get 'white_list', action: :edit_white_list
      post 'white_list', action: :update_white_list
    end
  end

  resources :templates, only: [:index]
  namespace :templates do
    resources :pushes, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :emails, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :system_messages, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :smses, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
  end

  resource :manual, controller: 'manual', only: [:show]
  namespace :manual do
    resources :system_messages, only: [:index, :create, :new]
    resources :emails, only: [:index, :create, :new] do
      collection do
        get 'good_items', to: 'emails#new_good_items'
        post 'good_items', to: 'emails#create_good_items'
      end
    end
    resources :statistics, only:[:index]
  end

  resources :user_feedback, only: [:index] do
    member do
      get 'feedback', action: :edit
      post 'feedback', action: :update
      get 'create_zendesk_ticket', action: :create_zendesk_ticket
    end
  end

  namespace :fmmc do
    resources :crons, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :tasks, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :triggers, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
  end

  namespace :tools do
    resources :items, only: [:index]
    resource :start_image, controller: 'start_image', only: [:edit, :update, :destroy]
    resource :home_banner, controller: 'home_banner', only: [:edit, :update, :destroy]
    resource :recommend_items, controller: 'recommend_items', only: [:create, :new]
  end

  namespace :tools do
    resources :items, only: [:index]
  end

  resource :api, controller: 'api', only: [] do
    collection do
      post 'country'
      post 'category'
    end
  end

  resources :item_tasks, only: [:index, :show, :create] do
    member do
      post 'complete', action: :complete
      post 'execute_action', action: :execute_action
    end
    collection do
      post 'create_and_execute', action: :create_and_execute
    end

    resources :item_task_comments
  end

  resources :item_operation_rules, only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get 'enable', action: :enable
      get 'disable', action: :disable
    end
  end

  namespace :smart_audit do
    resources :operators, only: [:index, :update] do
      post 'check_in'
      post 'check_out'
    end

    resources :board, only: [:index] do

      post 'change_category'

      post 'assign_data'

      collection do
        post 'pass_images',action: :pass_images
        get 'stat_info'
        get 'list_images'
        get 'list_items'
        post 'approve'
        post 'item_task_execute'
        post 'set_first_image'
      end
    end

    resources :owners, only: [:index]
    resources :tasks, only: [:index] do
      post 'quick_task_exec', action: :quick_task_exec
      member do
        post 'refresh', action: :query_task_state
      end
      collection do
        get 'get_rules'
        get 'get_img_audit_rules'
        get 'get_often_use_rules'
        post 'ajax', action: :item_task_ajax
      end
    end
  end

  namespace :smart_ads do

    resources :board, only: [:index] do

      collection do
        get 'update_info'
        get 'list_items'

        post "clear_current_feeds", action: :clear_product_feed
        post "select_feeds", action: :add_product_feed
      end
    end

  end

  get "es/list" => "es#list"
  get "es" => "es#index"

  get "my_506/bkuser" => "test#bkuser"
  get "my_506/execa" => "test#execa"
  get "my_506/q" => "test#test_q"
  get "my_506/agents" => "test#test_agents"
  get "my_506/empls" =>"test#test_empls"
  get "my_506/ph" =>"test#test_ph"
  get "my_506/wl" =>"test#test_wl"

end

app/models/backend/user.rb
class User < BackendBase
  belongs_to :user, class_name: 'EntityUser', foreign_key: 'user_id'

  def self.risk_scope
    where(internal_status: Settings.USER_INTERNAL_STATUSES.Risk)
  end
end

app/controllers/smart_review/users_controller.rb
class SmartReview::UsersController < ApplicationController
  def index
    respond_to do |format|
      format.json do
        user_info_data = {}

        EntityUser.where(id: params[:owner_ids]).select(:id, :nickname, :portrait).each do |user|
          user_id = user.id
          user_info_data[user_id] = {}
          user_info_data[user_id]['id'] = user_id
          user_info_data[user_id]['nickname'] = user.nickname
          user_info_data[user_id]['portrait'] = user.portrait
          user_info_data[user_id]['item_total'] = 0
          user_info_data[user_id]['item_listing_count'] = 0
          user_info_data[user_id]['item_sold_count'] = 0
          user_info_data[user_id]['item_unapproved_count'] = 0
          user_info_data[user_id]['item_unavailable_count'] = 0
          user_info_data[user_id]['item_unlisted_count'] = 0
        end

        EntityItem.where(user_id: user_info_data.keys).select(:id, :user_id, :state).find_each do |item|
          user_id = item.user_id
          user_info_data[user_id]['item_total'] += 1
          case item.state
            when Settings.PRODUCT_STATUSES.Listing
              user_info_data[user_id]['item_listing_count'] += 1
            when Settings.PRODUCT_STATUSES.Sold
              user_info_data[user_id]['item_sold_count'] += 1
            when Settings.PRODUCT_STATUSES.Unapproved
              user_info_data[user_id]['item_unapproved_count'] += 1
            when Settings.PRODUCT_STATUSES.Unavailable
              user_info_data[user_id]['item_unavailable_count'] += 1
            when Settings.PRODUCT_STATUSES.Unlisted
              user_info_data[user_id]['item_unlisted_count'] += 1
          end
        end

        User.where(user_id: user_info_data.keys)
            .where(internal_status: Settings.USER_INTERNAL_STATUSES.Risk)
            .select(:id, :user_id, :reason).find_each do |user|
          user_id = user.user_id
          user_info_data[user_id]['risk'] = user.reason
        end

        render json: user_info_data.values()
      end
    end
  end
end

app/controllers/users/review_reports_controller.rb
class Users::ReviewReportsController < ApplicationController

  before_action :get_review_report, only: [:show, :update, :create_zendesk_ticket]

  def index
    @review_reports_grid = initialize_grid(
        SpamReviewreportrecord,
        include: [:review],
        order: 'spam_reviewreportrecord.id',
        order_direction: 'desc',
        per_page: Settings.USER_REVIEWS_PER_PAGE)

    @unprocessed_reports = SpamReviewreportrecord.where(is_processed: 0).size
    @processed_reports = SpamReviewreportrecord.where(is_processed: 1).size
    @report_reason_options_for_select = SpamReportreason.review_report_reasons()
  end

  def show
    @reporter = EntityUser.select(:id, :nickname).find(@review_report.reporter_id)

  end

  def update
    is_success_flag = false
    message = ""
    begin
      is_send_flag = params[:is_send_flag] == '1' ? true : false
      is_ok = params[:is_ok] == '1' ? true : false
      is_success_flag, message = Utils::UserReviewReportOps.process(@review_report,
                                                                    session[:current_admin_id],
                                                                    session[:current_admin_username],
                                                                    params[:system_message_content],
                                                                    params[:push_content],
                                                                    is_send_flag,
                                                                    is_ok)
    end while false

    if is_success_flag
      flash[:success] = message
    else
      flash[:error] = message
    end
    redirect_to users_review_reports_path(
                    wice_grid_custom_filter_params(
                        grid_name: 'grid', attribute: 'is_processed', value: 'f'
                    ))
  end

  def create_zendesk_ticket
    is_success_flag, message = Utils::UserReviewReportOps.create_zendesk_ticket(@review_report)
    if is_success_flag
      flash[:success] = message
    else
      flash[:error] = message
    end

    redirect_to :back
  end

  def review_report_ajax
    case params[:fn]
      when "sm_push_template_content"
        trigger_name = ''
        case params[:is_ok]
          when '1'
            trigger_name = Settings.TRIGGER_TEMP_NAMES.UserReviewReportOkReporter
          when '0'
            trigger_name = Settings.TRIGGER_TEMP_NAMES.UserReviewReportDeleteReporter
        end
        data = Utils::UserReviewReportOps.get_template_contents(trigger_name)
        respond_to do |format|
          format.json { render json: data }
        end
      when "processors"
        data = BkUserReviewReportAuditHistory.where(review_report_id: params[:report_ids])
                   .pluck(:review_report_id, :admin)
                   .to_h
        respond_to do |format|
          format.json { render json: data }
        end
    end
  end

  private
  def get_review_report
    @review_report = SpamReviewreportrecord.find(params[:id])
  end
end

app/controllers/users/reviews_controller.rb
class Users::ReviewsController < ApplicationController
  def index
    @user_reviews_grid = initialize_grid(ReviewReview,
                                         include: [:reviewer, :reviewee],
                                         order: 'review_review.id',
                                         order_direction: 'desc',
                                         per_page: Settings.USER_REVIEWS_PER_PAGE)
  end

  def update
    is_send_reviewee = false
    if params[:is_send_reviewee] == '1'
      is_send_reviewee = true
    end
    review = ReviewReview.find(params[:id])
    is_success_flag, message = Utils::UserReviewOps.approve(review,
                                                            session[:current_admin_id],
                                                            session[:current_admin_username],
                                                            params[:system_message_content],
                                                            params[:push_content],
                                                            is_send_reviewee)
    if is_success_flag
      flash[:success] = message
    else
      flash[:error] = message
    end

    redirect_to request.referer
  end

  def destroy
    review = ReviewReview.find(params[:id])
    is_success_flag, message = Utils::UserReviewOps.disapprove(review,
                                                               session[:current_admin_id],
                                                               session[:current_admin_username],
                                                               params[:reason])
    if is_success_flag
      flash[:success] = message
    else
      flash[:error] = message
    end

    redirect_to request.referer
  end

  def review_ajax
    @review = ReviewReview.find(params[:id])
    case params[:fn]
      when "approve_window"
        trigger_name = Settings.TRIGGER_TEMP_NAMES.UserReviewReviewee
        template_contents = Utils::UserReviewOps.get_template_contents(trigger_name, @review)
        @push_template_content = template_contents['push_content']
        @system_message_template_content = template_contents['system_message_content']
        respond_to do |format|
          format.html { render "approve_window", layout: false }
        end
      when "disapprove_window"
        respond_to do |format|
          format.html { render "disapprove_window", layout: false }
        end
    end
  end

end

app/helpers/smart_review/users_helper.rb
module SmartReview::UsersHelper
end

app/helpers/users/review_reports_helper.rb
module Users::ReviewReportsHelper
  def review_report_get_report_ticket_json(report_ids=[])
    report_tickets = {}
    BkReviewReportZendeskTicket.select(:report_id, :ticket_id).where(report_id: report_ids).each do |rt|
      report_tickets[rt.report_id.to_s] = {ticket_id: rt.ticket_id}
    end
    report_tickets.to_json
  end
end

app/helpers/users/reviews_helper.rb
module Users::ReviewsHelper
end

app/helpers/users/subscriptions_helper.rb
module Users::SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def isTabActive(tab_name)
    @active_tab == tab_name ? 'active':''
  end

  def user_thumb_image_tag(user)
    image_content_tag = image_tag_content_100_100(image_url: user.portrait)
    link_to(image_content_tag, portrait_user_path(user), method: :get,
            remote: true) + content_tag(:span, user.nickname, class: "help-block text-center")
  end

  def user_attr_key(user, key)
    case key
      when 'os'
        'register_os'
      when 'os_version'
        'register_os_version'
      when 'app_version'
        'register_app_version'
      when 'device'
        'register_device'
      else
        key
    end.humanize
  end

  def user_attr_value(user, attr)
    case attr
      when 'gender'
        Settings.USER_GENDER.invert[user.gender]
      else
        user.send(attr)
    end
  end

  def user_wice_grid_risk_ids(grid)
    risk_user_ids = []
    grid.current_page_records.each do |u|
      risk_user_ids << u.id.to_s if u.user_info.present? and u.user_info.internal_status == Settings.USER_INTERNAL_STATUSES.Risk
    end
    return risk_user_ids
  end
end

app/views/users/reviews/approve_window.html.erb
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <%= form_tag users_review_path(@review), method: :put, role: 'form' do %>
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">
              &times;
            </button>
            <h4 class="modal-title" id="disapproveLabel">
              ApproveReview
            </h4>
          </div>
          <div class="modal-body">
            <% if @review.state == Settings.USER_REVIEW_STATES.PendingReview %>
                <div class="form-group">
                  <div class="col-md-offset-2">
                    <p>
                      <%= check_box_tag "is_send_reviewee", "1", true %>
                      Send Message to reviewee
                    </p>
                  </div>
                </div>
                <div class="form-group">
                  <%= label_tag 'system_message_content' %>
                  <div class="col-md-offset-2">
                    <%= text_area_tag 'system_message_content', @system_message_template_content, required: true, class: "form-control" %>
                  </div>
                </div>
                <div class="form-group">
                  <%= label_tag 'push_content' %>
                  <div class="col-md-offset-2">
                    <%= text_area_tag 'push_content', @push_template_content, required: true, maxlength: 120, class: "form-control" %>
                  </div>
                </div>

            <% elsif @review.state == Settings.USER_REVIEW_STATES.Disapprove %>
                <div>
                  <p>
                    Are you confirm?
                  </p>
                </div>

            <% end %>
          </div>
          <div class="modal-footer">
            <%= submit_tag 'Confirm', class: 'btn btn-md btn-primary' %>
            <button type="button" class="btn btn-md btn-default" data-dismiss="modal">
              Cancel
            </button>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/reviews/disapprove_window.html.erb
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <%= form_tag users_review_path(@review), method: :delete, role: 'form' do %>
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">
              &times;
            </button>
            <h4 class="modal-title" id="disapproveLabel">
              DisapproveReview
            </h4>
          </div>
          <div class="modal-body">
            <%= text_area_tag 'reason', nil, required: true, class: "form-control", placeholder: 'Please input disapprove reason ...' %>
          </div>
          <div class="modal-footer">
            <%= submit_tag 'Confirm', class: 'btn btn-md btn-primary' %>
            <button type="button" class="btn btn-md btn-default" data-dismiss="modal">
              Cancel
            </button>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/reviews/index.html.erb
<h2> User Review List </h2>

<hr/>

<%= grid(@user_reviews_grid) do |g|

  g.column name: 'ID', attribute: 'id'

  g.column name: "Score", attribute: 'score'

  g.column name: 'Text', attribute: 'comment', html: {class: 'col-md-2'}

  g.column name: 'From', attribute: 'nickname', model: 'EntityUser' do |task|
    link_to user_path(task.reviewer_id) do
      content_tag(:p) do
        task.reviewer.nickname
      end + content_tag(:p) do
        "ID:#{task.reviewer_id}#{'(S)' if task.direction == Settings.UserReview.Direction.SellerToBuyer}"
      end
    end if task.reviewer.present?
  end

  g.column name: 'To', attribute: 'nickname', model: 'EntityUser', table_alias: 'reviewee_review_review' do |task|
    link_to user_path(task.target_user) do
      content_tag(:p) do
        task.reviewee.nickname
      end + content_tag(:p) do
        "ID:#{task.target_user}#{'(S)' if task.direction == Settings.UserReview.Direction.BuyerToSeller}"
      end
    end if task.reviewee.present?
  end

  g.column name: 'Direction', attribute: 'direction', custom_filter: Settings.UserReview.Direction.to_a do |task|
    Settings.UserReview.Direction.invert[task.direction]
  end

  g.column name: 'Item', attribute: 'item_id', html: {class: 'col-md-1'} do |task|
    link_to task.item_id, product_path(task.item_id)
  end

  g.column name: 'ModifiedTime', attribute: 'last_updated_at', html: {class: 'col-md-2'}

  g.column name: 'UpdateTime', attribute: 'updated_at', html: {class: 'col-md-2'}

  g.column name: 'State', attribute: 'state', custom_filter: Settings.USER_REVIEW_STATES.to_a, html: {class: 'col-md-1'} do |task|
    Settings.USER_REVIEW_STATES.invert[task.state]
  end

  g.column html: {class: 'col-md-4'} do |task|
    content_tag(:div, class: 'pull-left') do
      if task.state != Settings.USER_REVIEW_STATES.Approve
        button_tag "Approve", data: {review_id: task.id}, class: "user-review-approve btn btn-sx btn-success"
      end
    end + content_tag(:div, class: 'pull-right') do
      if task.state != Settings.USER_REVIEW_STATES.Disapprove
        button_tag "Disapprove", data: {review_id: task.id}, class: "user-review-disapprove btn btn-sx btn-danger"
      end
    end
  end

end -%>

<script>
    $('.user-review-approve').click(function () {
        console.log('user review approve');
        var review_id = $(this).data('review-id');
        console.log(review_id);
        $.ajax({
            url: "<%= ajax_users_reviews_path(fn: "approve_window") %>",
            type: "GET",
            data: {id: review_id},
            cache: false,
            timeout: <%= Settings.AJAX.Timeout %>,
            success: function (data) {
                $(data).modal('show');
            },
            error: function (xhr, status, error) {
                alert(status + '.Please try again.');
            }
        });
    });
    $('.user-review-disapprove').click(function () {
        console.log('user review disapprove');
        var review_id = $(this).data('review-id');
        console.log(review_id);
        $.ajax({
            url: "<%= ajax_users_reviews_path(fn: "disapprove_window") %>",
            type: "GET",
            data: {id: review_id},
            cache: false,
            timeout: <%= Settings.AJAX.Timeout %>,
            success: function (data) {
                $(data).modal('show');
            },
            error: function (xhr, status, error) {
                alert(status + '.Please try again.');
            }
        });
    });
    $('input#grid_f_entity_user_nickname').attr("placeholder", "Nickname");
    $('input#grid_f_reviewee_review_review_nickname').attr("placeholder", "Nickname");
</script>