config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Settings.Sidekiq.username && password == Settings.Sidekiq.password
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  get 'welcome/index'

  root 'item_tasks#index'

  get 'index', to: redirect('welcome/index')

  get 'login' => 'welcome#login'
  post 'login' => 'welcome#create'

  get 'logout' => 'welcome#destroy'

  get 'logs' => 'trace_logs#index'

  get "fetch_product_feed" => "smart_ads/board#fetch_product_feed"

  namespace :users do
    resources :subscriptions, only: [:index, :new, :create, :edit, :update]
    resources :reviews do
      collection do
        get 'ajax', action: :review_ajax
      end
    end
    resources :review_reports do
      member do
        get 'create_zendesk_ticket', action: :create_zendesk_ticket
      end
      collection do
        get 'ajax', action: :review_report_ajax
      end
    end
  end
  resources :users, only: [:index, :show] do
    collection do
      post 'disable'
      post 'weight', action: :update_weight
      post 'risk', action: :user_risk

      get 'map'
      get 'disabled_state', action: :index_disabled_users
      get 'risk_state', action: :index_risk_users
      get 'bad_state', action: :index_bad_users

      get 'ajax', action: :user_ajax
    end

    member do
      post 'weight', action: :update_weight
      get 'portrait'
      post 'email'
    end

  end

  resources :products, only: [:index, :show] do
    collection do
      get 'hot_items', action: :index_hot_items
      get 'weight', action: :index_weight
      post 'weight', action: :update_weight
      put 'weight', action: :update_weight
      post 'categories', action: :update_categories
      post 'categories_new', action: :update_categories_new
      put 'approve'

      get 'map'
      get 'ajax', action: :product_ajax
    end

    member do
      get 'images'
      post 'categories', action: :update_categories
      get 'offers', action: :offers
      post 'weight', action: :update_weight
    end

    resource :state, controller: 'product_states', only: [:create] do
    end
  end

  resources :product_reports, only: [:index] do
    member do
      get 'feedback', action: :edit
      post 'feedback', action: :update
      get 'create_zendesk_ticket', action: :create_zendesk_ticket
    end
  end

  resources :user_reports, only: [:index] do
    member do
      get 'feedback', action: :edit
      post 'feedback', action: :update
      get 'create_zendesk_ticket', action: :create_zendesk_ticket
    end
  end

  resources :categories, as: 'category', except: [:destroy] do
    collection do
      get 'treeview'
    end

    member do
      get 'publish', action: :publish_category
      get 'draft', action: :draft_category
      get 'disable', action: :disable_category
      get 'enable', action: :enable_category
    end
  end

  resources :admins, only: [:index, :new, :create, :destroy, :edit, :show, :update] do
    resource :super_state, controller: 'admin_super_states', only: [:create, :destroy]
    member do
      get 'password', action: :password_edit
      post 'password', action: :password_update
    end
    collection do
      resources :schedules, controller: 'operator_schedules'
      get 'item_risk_keywords', action: :edit_item_risk_keywords
      post 'item_risk_keywords', action: :update_item_risk_keywords
      get 'white_list', action: :edit_white_list
      post 'white_list', action: :update_white_list
    end
  end

  resources :templates, only: [:index]
  namespace :templates do
    resources :pushes, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :emails, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :system_messages, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :smses, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
  end

  resource :manual, controller: 'manual', only: [:show]
  namespace :manual do
    resources :system_messages, only: [:index, :create, :new]
    resources :emails, only: [:index, :create, :new] do
      collection do
        get 'good_items', to: 'emails#new_good_items'
        post 'good_items', to: 'emails#create_good_items'
      end
    end
    resources :statistics, only:[:index]
  end

  resources :user_feedback, only: [:index] do
    member do
      get 'feedback', action: :edit
      post 'feedback', action: :update
      get 'create_zendesk_ticket', action: :create_zendesk_ticket
    end
  end

  namespace :fmmc do
    resources :crons, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :tasks, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :triggers, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
  end

  namespace :tools do
    resources :items, only: [:index]
    resource :start_image, controller: 'start_image', only: [:edit, :update, :destroy]
    resource :home_banner, controller: 'home_banner', only: [:edit, :update, :destroy]
    resource :recommend_items, controller: 'recommend_items', only: [:create, :new]
  end

  namespace :tools do
    resources :items, only: [:index]
  end

  resource :api, controller: 'api', only: [] do
    collection do
      post 'country'
      post 'category'
    end
  end

  resources :item_tasks, only: [:index, :show, :create] do
    member do
      post 'complete', action: :complete
      post 'execute_action', action: :execute_action
    end
    collection do
      post 'create_and_execute', action: :create_and_execute
    end

    resources :item_task_comments
  end

  resources :item_operation_rules, only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get 'enable', action: :enable
      get 'disable', action: :disable
    end
  end

  namespace :smart_audit do
    resources :operators, only: [:index, :update] do
      post 'check_in'
      post 'check_out'
    end

    resources :board, only: [:index] do

      post 'change_category'

      post 'assign_data'

      collection do
        post 'pass_images',action: :pass_images
        get 'stat_info'
        get 'list_images'
        get 'list_items'
        post 'approve'
        post 'item_task_execute'
        post 'set_first_image'
      end
    end

    resources :owners, only: [:index]
    resources :tasks, only: [:index] do
      post 'quick_task_exec', action: :quick_task_exec
      member do
        post 'refresh', action: :query_task_state
      end
      collection do
        get 'get_rules'
        get 'get_img_audit_rules'
        get 'get_often_use_rules'
        post 'ajax', action: :item_task_ajax
      end
    end
  end

  namespace :smart_ads do

    resources :board, only: [:index] do

      collection do
        get 'update_info'
        get 'list_items'

        post "clear_current_feeds", action: :clear_product_feed
        post "select_feeds", action: :add_product_feed
      end
    end

  end

  get "es/list" => "es#list"
  get "es" => "es#index"

  get "my_506/bkuser" => "test#bkuser"
  get "my_506/execa" => "test#execa"
  get "my_506/q" => "test#test_q"
  get "my_506/agents" => "test#test_agents"
  get "my_506/empls" =>"test#test_empls"
  get "my_506/ph" =>"test#test_ph"
  get "my_506/wl" =>"test#test_wl"

end

app/models/backend/item_operation_rule.rb
class ItemOperationRule < BackendBase
  belongs_to :target_rule, class_name: 'ItemOperationRule', foreign_key: 'target_rule_id'
  has_many   :source_rules, class_name: 'ItemOperationRule', foreign_key: 'target_rule_id'

  def is_enabled?
    return self.status
  end

  def is_keep_audit_state?
    return self.is_keep_audit_state
  end

  def self.operation_types
    operation_types = self.all.map { |rule| rule.name }
    operation_types << Settings.ITEM_TASK_TYPE.NotDefined
    return operation_types
  end

end

app/controllers/item_operation_rules_controller.rb
class ItemOperationRulesController < ApplicationController

  before_action :get_item_operation_rule, only: [:show, :edit, :update, :disable, :enable]

  def index
    @rules_grid = initialize_grid(
        ItemOperationRule,
        per_page: Settings.TASKS_PER_PAGE)
  end

  def new
    @rule = ItemOperationRule.new()
    @auto_complete_params = {}
    @show_type_checked_states = populate_checked_states(0)
  end

  def create
    @rule = ItemOperationRule.new(rule_params)

    if @rule.save()
      redirect_to item_operation_rules_path
    else
      render 'new'
    end
  end

  def show

  end

  def edit
    @auto_complete_params = {delay_time: @rule.delay_time,
                             action_type: @rule.action_type,
                             target_weight: @rule.target_weight,
                             target_rule_id: @rule.target_rule_id}

    # populate the check box checked_state
    @show_type_checked_states = populate_checked_states(@rule.show_type)
  end

  def update
    if @rule.update(rule_params)
      redirect_to item_operation_rule_path(@rule)
    else
      render 'edit'
    end
  end

  def disable
    @rule.status = 0
    @rule.save()

    redirect_to item_operation_rules_path
  end

  def enable
    @rule.status = 1
    @rule.save()

    redirect_to item_operation_rules_path
  end

  private
  def rule_params
    rule = params.require(:rule).permit(:name, :is_keep_audit_state,
                                        :action, :lower_weight_value,
                                        :notify_user, :push_message,
                                        :email_title, :email_and_system_message,
                                        :delay_time, :action_type,
                                        :target_weight, :target_rule_id)
    rule[:target_weight] = nil unless rule.has_key?(:target_weight)
    rule[:target_rule_id] = nil unless rule.has_key?(:target_rule_id)

    # transform show type name to value (default: 0)
    rule[:show_type] = trans_show_type_value(params[:show_type_names])

    return rule
  end

  def get_item_operation_rule
    @rule = ItemOperationRule.find(params[:id])
  end

  def trans_show_type_value(show_type_names)
    if show_type_names.nil?
      return 0
    else
      return ((show_type_names[:do_not_show].nil? ? 0 : show_type_names[:do_not_show].to_i) +
          (show_type_names[:image_audit].nil? ? 0 : show_type_names[:image_audit].to_i) +
          (show_type_names[:often_use].nil? ? 0 : show_type_names[:often_use].to_i))
    end
  end

  def populate_checked_states(show_type_value)
    show_type_checked_states = {}
    value = show_type_value.to_i
    if value == 0
      show_type_checked_states = {do_not_show: false, image_audit: false, often_use: false}
    else
      show_type_checked_states[:do_not_show] = value & Settings.ItemOperationRules.ShowType.DoNotShow == 0 ? false : true
      show_type_checked_states[:image_audit] = value & Settings.ItemOperationRules.ShowType.ImageAudit == 0 ? false : true
      show_type_checked_states[:often_use] = value & Settings.ItemOperationRules.ShowType.OftenUse == 0 ? false : true
    end
    show_type_checked_states
  end
end

app/views/item_operation_rules/_form.html.erb
<%= form_for @rule, as: :rule, html: {class: 'form-horizontal', role: 'form'} do |f| %>

    <% if @rule.errors.any? %>
        <div class="alert alert-danger">
          <h3><%= pluralize(@rule.errors.size, "error") %></h3>
          <ul>
            <% @rule.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label "Rule Name", class: 'col-md-3 control-label' %>
      <div class="col-md-5">
        <%= f.text_field :name, class: 'form-control', autofocus: true, required: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-3 col-md-5">
        <%= f.check_box :is_keep_audit_state %>
        Do not change status to <b>InReview</b>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Show Type", class: 'col-md-3 control-label' %>
      <div class="col-md-9">
          <div class="row col-md-9">
            <%= check_box_tag('show_type_names[do_not_show]', Settings.ItemOperationRules.ShowType.DoNotShow, @show_type_checked_states[:do_not_show]) %>
            <%= label_tag('show_type_names[do_not_show]', "Do not show on Manal Execution Selection List") %>
            </div>
          <div class="row col-md-9">
            <%= check_box_tag('show_type_names[image_audit]', Settings.ItemOperationRules.ShowType.ImageAudit,  @show_type_checked_states[:image_audit]) %>
            <%= label_tag('show_type_names[image_audit]', "Show on ImageAudit")%></div>
          <div class="row col-md-9">
            <%= check_box_tag('show_type_names[often_use]', Settings.ItemOperationRules.ShowType.OftenUse,  @show_type_checked_states[:often_use]) %>
            <%= label_tag('show_type_names[often_use]',"Often use") %></div>
       </div>
    </div>

    <div class="form-group">
      <%= f.label :action, class: 'col-md-3 control-label' %>
      <div class="col-md-9">
        <div class="row col-md-3">
          <%= f.radio_button :action, 'lower_weight', checked: @rule.action == 'lower_weight' %><%= label_tag 'Lower Weight' %>
        </div>
        <div class="row col-md-2">
          <%= f.select :lower_weight_value, [0, 1, 2, 3, 4], {}, class: 'form-control', require: true %>
        </div>
        <div class="row col-md-9">
          <%= f.radio_button :action, 'take_down', checked: @rule.action == 'take_down' %><%= label_tag 'Take down' %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :notify_user, class: 'col-md-3 control-label' %>
      <div class="col-md-2">
        <%= f.select :notify_user, options_for_select({True: 1, False: 0}, @rule.notify_user), {}, {class: 'form-control'} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Push message", class: 'col-md-3 control-label' %>
      <div class="col-md-6">
        <%= f.text_area :push_message, cols: 40, rows: 2, class: 'form-control', required: true, maxlength: 80 %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Email title", class: 'col-md-3 control-label' %>
      <div class="col-md-6">
        <%= f.text_field :email_title, class: 'form-control', autofocus: true, required: true, maxlength: 80 %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "System message & first part of email", class: 'col-md-3 control-label' %>
      <div class="col-md-6">
        <%= f.text_area :email_and_system_message, cols: 40, rows: 5, class: 'form-control', required: true %>
        <span class="help-block">variables: ${item_title}  -  title of item</span>
      </div>
    </div>

    <div class="form-group hidden">
      <div class="col-md-offset-3 col-md-6">
        <label>
          <input type="checkbox" name="is_auto_complete" value="1">
          Auto Complete if no modify
        </label>

        <div id="auto_complete_box" style="">

        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-3 col-md-5">
        <%= f.submit class: 'btn btn-primary' %>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Cancel', item_operation_rules_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

<script id="tmpl_auto_complete_box" type="text/x-jquery-tmpl">
          <p>
            DelayTime:
            <input type="text" name="rule[delay_time]" required="required">
            hours later
          </p>

          <p id="auto_approve_complete_box">
            <input type="radio" name="rule[action_type]" value="<%= Settings.ItemOperationRules.ActionType.ApproveAndComplete %>" required="required">
            Approve & Complete

            <div class="auto_complete_action" id="change_weight_box" style="padding-left: 15px;">

            </div>
          </p>

          <p id="change_rule_box">
            <input type="radio" name="rule[action_type]" value="<%= Settings.ItemOperationRules.ActionType.ExchangeRule %>" required="required">
            Execute another rule

            <div class="auto_complete_action" id="target_rule_id_box" style="padding-left: 15px;">

            </div>
          </p>


</script>
<script id="tmpl_change_weight_box" type="text/x-jquery-tmpl">
                <input type="checkbox" name="rule[change_weight]" value="1">
                Change weight
                <div id="target_weight_box" style="padding-left: 15px;">

                </div>


</script>
<script id="tmpl_target_weight_box" type="text/x-jquery-tmpl">
                Target weight:
                <input type="text" name="rule[target_weight]" required="required">


</script>
<script id="tmpl_target_rule_id_box" type="text/x-jquery-tmpl">
                Rules:
                <%= select_tag "rule[target_rule_id]",
                               options_for_select(ItemOperationRule.where(status: true).order(:name).pluck(:name, :id)),
                               prompt: 'Please select a rule',
                               required: true %>
</script>
<script>
    var auto_complete_params = <%= raw auto_complete_params.to_json %>;

    function init_func() {
        $('input[name="is_auto_complete"]').click(function () {
            if ($(this).prop('checked') === false) {
                $('#auto_complete_box').removeAttr('style').html('');
            } else {
                $('#tmpl_auto_complete_box').tmpl().appendTo('#auto_complete_box');
                $('#auto_complete_box').attr('style', "padding-left: 15px; padding-top: 15px; border: 1px solid #cccccc;border-radius: 4px;");
                if (auto_complete_params['delay_time'] !== undefined && auto_complete_params['delay_time'] !== null) {
                    $('input[name="rule[delay_time]"]').val(auto_complete_params['delay_time']);
                }
                if (auto_complete_params['action_type'] !== undefined && auto_complete_params['action_type'] !== null) {
                    if (auto_complete_params['action_type'] === <%= raw Settings.ItemOperationRules.ActionType.ApproveAndComplete %>) {
                        if ($('p#auto_approve_complete_box > input[name="rule[action_type]"]').prop('checked') === false) {
                            $('p#auto_approve_complete_box > input[name="rule[action_type]"]').click();
                        }
                    } else if (auto_complete_params['action_type'] === <%= raw Settings.ItemOperationRules.ActionType.ExchangeRule %>) {
                        if ($('p#change_rule_box > input[name="rule[action_type]"]').prop('checked') === false) {
                            $('p#change_rule_box > input[name="rule[action_type]"]').click();
                        }
                    }
                }
            }
        });

        $('#auto_complete_box').on('click', 'input[name="rule[action_type]"]', function () {
            console.log('click input[name="rule[action_type]"]');
            console.log($(this));
            $('input[name="rule[action_type]"]').each(function () {
                console.log($(this).parent().text() + ':' + $(this).prop('checked'));
            });
            console.log($('input[name="rule[action_type]"]:checked').parent().text());

            var checked_value = $(this).val();
            console.log(checked_value);
            $('div.auto_complete_action').each(function () {
                $(this).html('');
            });
            if (checked_value === '<%= Settings.ItemOperationRules.ActionType.ApproveAndComplete %>') {
                $('#tmpl_change_weight_box').tmpl().appendTo('#change_weight_box');
                if (auto_complete_params['target_weight'] !== undefined && auto_complete_params['target_weight'] !== null) {
                    $('#change_weight_box > input[name="rule[change_weight]"]').click();
                }
            } else if (checked_value === '<%= Settings.ItemOperationRules.ActionType.ExchangeRule %>') {
                $('#tmpl_target_rule_id_box').tmpl().appendTo('#target_rule_id_box');
                if (auto_complete_params['target_rule_id'] !== undefined && auto_complete_params['target_rule_id'] !== null) {
                    $('select[name="rule[target_rule_id]"] > option[value="' + auto_complete_params['target_rule_id'] + '"]').attr('selected', 'selected');
                }
            }
        });

        $('#auto_complete_box').on('click', 'input[name="rule[change_weight]"]', function () {
            if ($(this).prop('checked') === false) {
                $('#target_weight_box').html('');
            } else {
                $(this).prop('checked', true);
                $('#tmpl_target_weight_box').tmpl().appendTo('#target_weight_box');
                if (auto_complete_params['target_weight'] !== undefined && auto_complete_params['target_weight'] !== null) {
                    $('#target_weight_box > input[name="rule[target_weight]"]').val(auto_complete_params['target_weight']);
                }
            }
        });

        $('input[name="rule[action]"]').click(function () {
            var value = $(this).val();
            if (value === "lower_weight") {
                $('#auto_complete_box').parents('.form-group').removeClass('hidden');
                if (auto_complete_params['delay_time'] !== undefined && auto_complete_params['delay_time'] !== null) {
                    if ($('input[name="is_auto_complete"]').prop('checked') === false) {
                        $('input[name="is_auto_complete"]').click();
                    }
                }
            } else {
                $('#auto_complete_box').parents('.form-group').addClass('hidden');
                if ($('input[name="is_auto_complete"]').prop('checked')) {
                    $('input[name="is_auto_complete"]').click();
                }
            }
        });

        $('input[name="rule[action]"]:checked').click();
    }
    init_func();
</script>

app/views/item_operation_rules/edit.html.erb
<h1>Edit Item Operation Rule</h1>

<hr/>

<%= render partial: 'form', locals: {auto_complete_params: @auto_complete_params} %>

app/views/item_operation_rules/index.html.erb
<h2> Item Operation Rules </h2>

<hr/>

<div class="btn-toolbar" role="toolbar">
  <div class="btn-group pull-right">
     <%= link_to "Create", new_item_operation_rule_path, class: "btn btn-md btn-primary" %>
  </div>
</div>


<%= grid(@rules_grid) do |g|

  g.column name: 'ID', attribute: 'id',
           filter: false, ordering: false

  g.column name: "Name", attribute: 'name',
           filter: false, ordering: false, html: {class: 'col-md-5'} do |task|
    link_to task.name, item_operation_rule_path(task)
  end

  g.column name: 'Action', attribute: 'action',
           filter: false, ordering: false

  g.column name: 'Notify User', attribute: 'notify_user',
           filter: false, ordering: false

  # g.column name: 'Push Message', attribute: 'push_message',
  #          filter: false, ordering: false, html: {class: 'col-md-2'}
  #
  # g.column name: 'Long Message Title', attribute: 'notify_long_message_title',
  #          filter: false, ordering: false, html: {class: 'col-md-2'}
  #
  # g.column name: 'Long Message', attribute: 'notify_long_message',
  #          filter: false, ordering: false, html: {class: 'col-md-2'}

  g.column name: 'Edit' do |task|
    link_to 'Edit', edit_item_operation_rule_path(task), class: 'btn btn-sm btn-success'
  end

  g.column name: "Status", attribute: 'status', filter: false, ordering: false do |task|
    task.status ? "Enabled" : "Disabled"
  end

  g.column do |task|
    if task.is_enabled?
      link_to 'Disable', disable_item_operation_rule_path(task), class: 'btn btn-sm btn-warning'
    else
      link_to 'Enable', enable_item_operation_rule_path(task), class: 'btn btn-sm btn-success'
    end
  end

end -%>

app/views/item_operation_rules/new.html.erb
<h1>Create Item Operation Rule</h1>

<hr/>

<%= render partial: 'form', locals: {auto_complete_params: @auto_complete_params} %>

app/views/item_operation_rules/show.html.erb
<h2>Item Operation Rule</h2>

<hr/>

<div class="btn-toolbar" role="toolbar">
  <div class="btn-group pull-right">
    <%= link_to "Edit", edit_item_operation_rule_path(@rule), class: "btn btn-md btn-primary" %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-bordered">
    <tbody>
    <% @rule.attributes.each_pair do |key, value| %>
        <tr>
          <td align="right" class="active col-md-4"><strong><%= key.humanize %></strong></td>
          <td align="left" class="col-md-8">
            <%= value %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>