config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Settings.Sidekiq.username && password == Settings.Sidekiq.password
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  get 'welcome/index'

  root 'item_tasks#index'

  get 'index', to: redirect('welcome/index')

  get 'login' => 'welcome#login'
  post 'login' => 'welcome#create'

  get 'logout' => 'welcome#destroy'

  get 'logs' => 'trace_logs#index'

  get "fetch_product_feed" => "smart_ads/board#fetch_product_feed"

  namespace :users do
    resources :subscriptions, only: [:index, :new, :create, :edit, :update]
    resources :reviews do
      collection do
        get 'ajax', action: :review_ajax
      end
    end
    resources :review_reports do
      member do
        get 'create_zendesk_ticket', action: :create_zendesk_ticket
      end
      collection do
        get 'ajax', action: :review_report_ajax
      end
    end
  end
  resources :users, only: [:index, :show] do
    collection do
      post 'disable'
      post 'weight', action: :update_weight
      post 'risk', action: :user_risk

      get 'map'
      get 'disabled_state', action: :index_disabled_users
      get 'risk_state', action: :index_risk_users
      get 'bad_state', action: :index_bad_users

      get 'ajax', action: :user_ajax
    end

    member do
      post 'weight', action: :update_weight
      get 'portrait'
      post 'email'
    end

  end

  resources :products, only: [:index, :show] do
    collection do
      get 'hot_items', action: :index_hot_items
      get 'weight', action: :index_weight
      post 'weight', action: :update_weight
      put 'weight', action: :update_weight
      post 'categories', action: :update_categories
      post 'categories_new', action: :update_categories_new
      put 'approve'

      get 'map'
      get 'ajax', action: :product_ajax
    end

    member do
      get 'images'
      post 'categories', action: :update_categories
      get 'offers', action: :offers
      post 'weight', action: :update_weight
    end

    resource :state, controller: 'product_states', only: [:create] do
    end
  end

  resources :product_reports, only: [:index] do
    member do
      get 'feedback', action: :edit
      post 'feedback', action: :update
      get 'create_zendesk_ticket', action: :create_zendesk_ticket
    end
  end

  resources :user_reports, only: [:index] do
    member do
      get 'feedback', action: :edit
      post 'feedback', action: :update
      get 'create_zendesk_ticket', action: :create_zendesk_ticket
    end
  end

  resources :categories, as: 'category', except: [:destroy] do
    collection do
      get 'treeview'
    end

    member do
      get 'publish', action: :publish_category
      get 'draft', action: :draft_category
      get 'disable', action: :disable_category
      get 'enable', action: :enable_category
    end
  end

  resources :admins, only: [:index, :new, :create, :destroy, :edit, :show, :update] do
    resource :super_state, controller: 'admin_super_states', only: [:create, :destroy]
    member do
      get 'password', action: :password_edit
      post 'password', action: :password_update
    end
    collection do
      resources :schedules, controller: 'operator_schedules'
      get 'item_risk_keywords', action: :edit_item_risk_keywords
      post 'item_risk_keywords', action: :update_item_risk_keywords
      get 'white_list', action: :edit_white_list
      post 'white_list', action: :update_white_list
    end
  end

  resources :templates, only: [:index]
  namespace :templates do
    resources :pushes, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :emails, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :system_messages, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :smses, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
  end

  resource :manual, controller: 'manual', only: [:show]
  namespace :manual do
    resources :system_messages, only: [:index, :create, :new]
    resources :emails, only: [:index, :create, :new] do
      collection do
        get 'good_items', to: 'emails#new_good_items'
        post 'good_items', to: 'emails#create_good_items'
      end
    end
    resources :statistics, only:[:index]
  end

  resources :user_feedback, only: [:index] do
    member do
      get 'feedback', action: :edit
      post 'feedback', action: :update
      get 'create_zendesk_ticket', action: :create_zendesk_ticket
    end
  end

  namespace :fmmc do
    resources :crons, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :tasks, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :triggers, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
  end

  namespace :tools do
    resources :items, only: [:index]
    resource :start_image, controller: 'start_image', only: [:edit, :update, :destroy]
    resource :home_banner, controller: 'home_banner', only: [:edit, :update, :destroy]
    resource :recommend_items, controller: 'recommend_items', only: [:create, :new]
  end

  namespace :tools do
    resources :items, only: [:index]
  end

  resource :api, controller: 'api', only: [] do
    collection do
      post 'country'
      post 'category'
    end
  end

  resources :item_tasks, only: [:index, :show, :create] do
    member do
      post 'complete', action: :complete
      post 'execute_action', action: :execute_action
    end
    collection do
      post 'create_and_execute', action: :create_and_execute
    end

    resources :item_task_comments
  end

  resources :item_operation_rules, only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get 'enable', action: :enable
      get 'disable', action: :disable
    end
  end

  namespace :smart_audit do
    resources :operators, only: [:index, :update] do
      post 'check_in'
      post 'check_out'
    end

    resources :board, only: [:index] do

      post 'change_category'

      post 'assign_data'

      collection do
        post 'pass_images',action: :pass_images
        get 'stat_info'
        get 'list_images'
        get 'list_items'
        post 'approve'
        post 'item_task_execute'
        post 'set_first_image'
      end
    end

    resources :owners, only: [:index]
    resources :tasks, only: [:index] do
      post 'quick_task_exec', action: :quick_task_exec
      member do
        post 'refresh', action: :query_task_state
      end
      collection do
        get 'get_rules'
        get 'get_img_audit_rules'
        get 'get_often_use_rules'
        post 'ajax', action: :item_task_ajax
      end
    end
  end

  namespace :smart_ads do

    resources :board, only: [:index] do

      collection do
        get 'update_info'
        get 'list_items'

        post "clear_current_feeds", action: :clear_product_feed
        post "select_feeds", action: :add_product_feed
      end
    end

  end

  get "es/list" => "es#list"
  get "es" => "es#index"

  get "my_506/bkuser" => "test#bkuser"
  get "my_506/execa" => "test#execa"
  get "my_506/q" => "test#test_q"
  get "my_506/agents" => "test#test_agents"
  get "my_506/empls" =>"test#test_empls"
  get "my_506/ph" =>"test#test_ph"
  get "my_506/wl" =>"test#test_wl"

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :find_category, only: [:edit, :update, :show, :publish_category, :draft_category, :disable_category, :enable_category]
  before_action :all_category_for_select, only: [:index, :edit, :new]

  def index
    @categories_grid = initialize_grid(
        EntityCategory,
        order: 'entity_category.order_num',
        order_direction: 'asc',
        include: [:parent],
        per_page: Settings.CATEGORIES_PER_PAGE)
    @all_category_for_display = @all_category_for_select.invert
  end

  def treeview
    url = URI('/products')
    @category_tree_data = EntityCategory.select(:id, :parent_id, :title).valid.map do |category|
      url.query = URI.encode_www_form([['grid[f][entity_category.id][]', category.id]])
      {id: category.id, pId: category.parent_id, name: category.title, target: '_blank', url: url.to_s}
    end
    @category_tree_data.unshift({id: Settings.TOP_CATEGORY['Top Category'], pId: nil, name: 'Root', open: true})
  end

  def new
    @category = EntityCategory.new
  end

  def create
    category_params = get_category_params()
    @category = EntityCategory.new(category_params)
    if @category.save
      flash[:success] = "Created '#{@category.title}' successfully."
      redirect_to category_path(@category)
    else
      flash[:error] = "Failed to create '#{@category.title}'"
      render 'new'
    end
  end

  def update
    category_params = get_category_params()
    log_info("Update the category '" + @category.title + "'")

    weight = category_params.delete(:weight)
    if weight.present?
      weight = weight.to_i
      if weight < Settings.WEIGHT.Min or weight > Settings.WEIGHT.Max
        flash[:warning] = 'Weight value is invalid.'
      end
    end

    if flash[:warning].present?
      render 'edit'
    else
      if @category.update(category_params)
        if weight != @category.weight
          ret = BackendApiREST.batch_update_category_weight(@category.id, weight)
          if ret[1].present?
            ret = JSON.load(ret[1])
            if ret["meta"]["result"] == "ok"
              flash[:success] = "Update the category '" + @category.title + "' successfully."
            else
              flash[:error] = "Failed to update some product's category weight(ids: #{ret["objects"]})."
            end
            redirect_to category_index_path
          else
            flash[:error] = "Failed to update category weight attribute"
            render 'edit'
          end
        else
          flash[:success] = "Update the category '" + @category.title + "' successfully."
          redirect_to category_index_path
        end
      else
        render 'edit'
      end
    end
  end

  def edit
  end

  def publish_category
    begin
      if @category.status == Settings.CATEGORY_STATUSES.Published
        flash[:success] = "Category '#{@category.title}' had been in publish status."
      else
        if @category.update(status: Settings.CATEGORY_STATUSES.Published, publish_date: Time.current)
          flash[:success] = "Publish category '#{@category.title}' successfully."
        else
          flash[:error] = "Failed to publish category '#{@category.title}'"
        end
      end
    end while false
    redirect_to :back
  end

  def draft_category
    begin
      if @category.status == Settings.CATEGORY_STATUSES.Draft
        flash[:success] = "Category '#{@category.title}' had been in draft status."
      else
        if @category.update(status: Settings.CATEGORY_STATUSES.Draft)
          flash[:success] = "Draft category '#{@category.title}' successfully."
        else
          flash[:error] = "Failed to draft category '#{@category.title}'"
        end
      end
    end while false
    redirect_to :back
  end

  def disable_category
    begin
      if @category.status == Settings.CATEGORY_STATUSES.Invalid
        flash[:success] = "Category '#{@category.title}' had been in disable status."
      else
        if @category.update(status: Settings.CATEGORY_STATUSES.Invalid)
          flash[:success] = "Disable category '#{@category.title}' successfully."
        else
          flash[:error] = "Failed to disable category '#{@category.title}'"
        end
      end
    end while false
    redirect_to :back
  end

  def enable_category
    begin
      if @category.status != Settings.CATEGORY_STATUSES.Invalid
        flash[:error] = "Category '#{@category.title}' had not been in disable status."
      else
        if @category.update(status: Settings.CATEGORY_STATUSES.Draft)
          flash[:success] = "Enable category '#{@category.title}' successfully."
        else
          flash[:error] = "Failed to enable category '#{@category.title}'"
        end
      end
    end while false
    redirect_to :back
  end

  private
  def find_category
    @category = EntityCategory.find(params[:id])
  end

  def all_category_for_select
    @all_category_for_select = Settings.TOP_CATEGORY.merge(EntityCategory.pluck(:title, :id).to_h)
  end

  def get_category_params
    params.require(:category).permit(:title, :description, :gender, :weight, :icon)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper

  def category_attr_value(category, key, value)
    case key
      when 'parent_id'
        category.parent.blank? ? Settings.TOP_CATEGORY.invert[Settings.TOP_CATEGORY["Top Category"]] : self.parent.title
      when 'status'
        Settings.CATEGORY_STATUSES.invert[value]
      when 'gender'
        Settings.USER_GENDER.invert[value]
      else
        value
    end
  end

end

app/views/categories/_form.html.erb
<div class="col-md-8">
  <%= form_for @category, as: 'category', url: form_url, method: form_method, html: {class: 'form-horizontal', role: 'form'} do |f| %>

      <% if @category.errors.any? %>
          <div class="warning">
                <h2><%= pluralize(@category.errors.size, "error") %> prohibited
                  this category from being saved:</h2>
            <ul>
              <% @category.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title, class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= f.text_field :title, class: 'form-control', maxlength: 50, required: true %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :icon, class: 'col-md-4 control-label' %>
        <div class="col-md-7">
          <%= f.url_field :icon, class: 'form-control', required: true %>
          <div class="progress progress-striped active" style="height: 3px; margin-bottom: 0;">
            <div class="progress-bar progress-bar-success" role="progressbar" style="width: 0%;">
            </div>
          </div>
        </div>
        <div class="col-md-1">
          <a class="btn btn-md btn-default pull-right" onclick="$('input.cloudinary-fileupload').click()">
            <i class="fa fa-upload"></i>
          </a>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :gender, class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= f.select :gender, options_for_select(Settings.USER_GENDER, @category.gender), {prompt: 'Please select an option'}, required: true, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :weight, class: 'col-md-4 control-label' %>
        <div id="change_weight" class="col-md-8">
          <%= f.text_field :weight, id: 'weight', required: true, class: 'form-control' %>
          <span class="help-block"><%= "Weight value range: #{Settings.WEIGHT.Min} ~ #{Settings.WEIGHT.Max}" %></span>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :description, class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= f.text_area :description, maxlength: 200, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-4 col-md-8">
          <%= f.submit id: 'save_weight', class: 'btn btn-primary' %>
          <%= link_to 'Cancel', :back, :class => 'btn btn-default' %>
        </div>
      </div>

  <% end %>
</div>
<div id="preview_image" class="thumbnail col-md-4 <%= 'hidden' if @category.icon.blank? %>">
  <%= image_tag_content_with_options(image_url: @category.icon) if @category.icon.present? %>
</div>

<from>
  <%= cl_image_upload_tag(:image, html: {class: 'hidden', style: 'padding: 6px 0;'}) %>
</from>

<%= cloudinary_js_config %>

<script>
    $('.cloudinary-fileupload').bind('fileuploadprogress', function(e, data) {
        if ($('div.progress-bar').hasClass('progress-bar-danger')) {
            $('div.progress-bar').removeClass('progress-bar-danger').addClass('progress-bar-success');
        }
        $('div.progress-bar').css('width', Math.round((data.loaded * 100.0) / data.total) + '%');
    });
    $('.cloudinary-fileupload').bind('cloudinarydone', function(e, data) {
        $('div#preview_image').html(
                $.cloudinary.image(data.result.public_id,
                        { format: data.result.format, version: data.result.version })
        );
        $('input#category_icon').val(data.result.url);
        $('div#preview_image').removeClass('hidden');
        return true;
    });
    $('.cloudinary-fileupload').bind('cloudinaryfail', function(e, data) {
        $('div.progress-bar').removeClass('progress-bar-success').addClass('progress-bar-danger');
        alert("upload fail!");
    });
</script>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<hr/>

<%= render partial: 'form', locals: { form_url: category_path(@category), form_method: :put } %>

app/views/categories/index.html.erb
<h2>Category List</h2>

<div class="btn-toolbar" role="toolbar">
  <div class="btn-group pull-right">
    <a role="button" class="btn btn-default btn-md" href="/categories/treeview"
       data-toggle="tooltip" data-placement="top" title="Show the tree view">
      <span class="glyphicon glyphicon-tree-conifer"></span>
      &nbsp;Tree View
    </a>
  </div>
  <div class="btn-group pull-right">
    <%= link_to 'Add Category', new_category_path, class: 'btn btn-primary btn-md', target: '_blank' %>
  </div>
</div>

<hr/>

<%= grid(@categories_grid) do |g|

  g.column name: 'ID', attribute: 'id'

  g.column name: 'Order', attribute: 'order_num', filter: false, html: {class: 'editable-order'}

  g.column name: 'Title', attribute: 'title', ordering: false, html: {class: 'col-md-2'} do |task|
    link_to task.title, category_path(task), target: '_blank'
  end

  g.column name: 'Gender', attribute: 'gender', html: {class: 'col-md-1'} do |task|
    Settings.USER_GENDER.invert[task.gender] if task.gender.present?
  end

  g.column name: 'Status', attribute: 'status', custom_filter: Settings.CATEGORY_STATUSES.to_a, html: {class: 'col-md-1'} do |task|
    Settings.CATEGORY_STATUSES.invert[task.status]
  end

  g.column name: 'Publish Date', attribute: 'publish_date', html: {class: 'col-md-1'} do |task|
    task.publish_date if task.publish_date
  end

  g.column name: 'Parent', attribute: 'parent_id',
           ordering: false, filter: false, html: {class: 'col-md-1'} do |task|
    @all_category_for_display[task.parent_id] if task.parent_id.present?
  end

  g.column name: 'Weight', attribute: 'weight', html: {class: 'col-md-1'}

  g.column name: 'Weight Update Time', attribute: 'weight_updated_at', html: {class: 'col-md-1'}

  g.column do |task|
    if task.publish? && !task.draft?
      link_to('Draft', draft_category_path(task),
              data: {confirm: 'Press OK to confirm.', disable_with: 'Processing...'},
              class: 'btn btn-sm btn-danger')
    elsif !task.publish? && task.draft?
      link_to('Publish', publish_category_path(task),
              data: {confirm: 'Press OK to confirm.', disable_with: 'Processing...'},
              class: 'btn btn-sm btn-success')
    end
  end

  g.column do |task|
    if task.invalid?
      link_to('Enable', enable_category_path(task),
              data: {confirm: 'Press OK to confirm.', disable_with: 'Processing...'},
              class: 'btn btn-sm btn-primary')
    else
      link_to('Disable', disable_category_path(task),
              data: {confirm: 'Press OK to confirm.', disable_with: 'Processing...'},
              class: 'btn btn-sm btn-warning')
    end
  end

end -%>

app/views/categories/new.html.erb
<h2>Add Category</h2>

<hr/>

<%= render partial: 'form', locals: { form_url: category_index_path, form_method: :post } %>

app/views/categories/show.html.erb
<h2>Category</h2>

<hr/>

<div class="col-md-8">
  <div class="btn-toolbar" role="toolbar">
    <div class="btn-group pull-right col-md-2">
      <%= link_to "Edit", edit_category_path(@category), class: "btn btn-md btn-danger btn-block" %>
    </div>
  </div>

  <div class="col-md-12">
    <table class="table table-bordered table-hover">
      <tbody>
      <% @category.attributes.each_pair do |key, value| %>
          <tr>
            <th align="right"><%= key.humanize %></th>
            <td>
              <%= category_attr_value(@category, key, value) %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<div id="preview_image" class="thumbnail col-md-4 <%= 'hidden' if @category.icon.blank? %>">
  <%= image_tag_content_with_options(image_url: @category.icon) if @category.icon.present? %>
</div>

app/views/categories/treeview.html.erb
<h2>Category Tree</h2>

<div class="btn-toolbar" role="toolbar">
  <div class="btn-group pull-right">
    <a role="button" class="btn btn-default btn-md" href="/categories"
       data-toggle="tooltip" data-placement="top" title="Show the edit view">
      <span class="glyphicon glyphicon-list"></span>
      &nbsp;List View
    </a>
  </div>
</div>

<hr/>

<div class="row">
  <div class="col-md-7">
    <%= ztree_category_tree_tag() %>
  </div>
</div>

<%= ztree_category_tree_js_tag(@category_tree_data.to_json) %>