config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Settings.Sidekiq.username && password == Settings.Sidekiq.password
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  get 'welcome/index'

  root 'item_tasks#index'

  get 'index', to: redirect('welcome/index')

  get 'login' => 'welcome#login'
  post 'login' => 'welcome#create'

  get 'logout' => 'welcome#destroy'

  get 'logs' => 'trace_logs#index'

  get "fetch_product_feed" => "smart_ads/board#fetch_product_feed"

  namespace :users do
    resources :subscriptions, only: [:index, :new, :create, :edit, :update]
    resources :reviews do
      collection do
        get 'ajax', action: :review_ajax
      end
    end
    resources :review_reports do
      member do
        get 'create_zendesk_ticket', action: :create_zendesk_ticket
      end
      collection do
        get 'ajax', action: :review_report_ajax
      end
    end
  end
  resources :users, only: [:index, :show] do
    collection do
      post 'disable'
      post 'weight', action: :update_weight
      post 'risk', action: :user_risk

      get 'map'
      get 'disabled_state', action: :index_disabled_users
      get 'risk_state', action: :index_risk_users
      get 'bad_state', action: :index_bad_users

      get 'ajax', action: :user_ajax
    end

    member do
      post 'weight', action: :update_weight
      get 'portrait'
      post 'email'
    end

  end

  resources :products, only: [:index, :show] do
    collection do
      get 'hot_items', action: :index_hot_items
      get 'weight', action: :index_weight
      post 'weight', action: :update_weight
      put 'weight', action: :update_weight
      post 'categories', action: :update_categories
      post 'categories_new', action: :update_categories_new
      put 'approve'

      get 'map'
      get 'ajax', action: :product_ajax
    end

    member do
      get 'images'
      post 'categories', action: :update_categories
      get 'offers', action: :offers
      post 'weight', action: :update_weight
    end

    resource :state, controller: 'product_states', only: [:create] do
    end
  end

  resources :product_reports, only: [:index] do
    member do
      get 'feedback', action: :edit
      post 'feedback', action: :update
      get 'create_zendesk_ticket', action: :create_zendesk_ticket
    end
  end

  resources :user_reports, only: [:index] do
    member do
      get 'feedback', action: :edit
      post 'feedback', action: :update
      get 'create_zendesk_ticket', action: :create_zendesk_ticket
    end
  end

  resources :categories, as: 'category', except: [:destroy] do
    collection do
      get 'treeview'
    end

    member do
      get 'publish', action: :publish_category
      get 'draft', action: :draft_category
      get 'disable', action: :disable_category
      get 'enable', action: :enable_category
    end
  end

  resources :admins, only: [:index, :new, :create, :destroy, :edit, :show, :update] do
    resource :super_state, controller: 'admin_super_states', only: [:create, :destroy]
    member do
      get 'password', action: :password_edit
      post 'password', action: :password_update
    end
    collection do
      resources :schedules, controller: 'operator_schedules'
      get 'item_risk_keywords', action: :edit_item_risk_keywords
      post 'item_risk_keywords', action: :update_item_risk_keywords
      get 'white_list', action: :edit_white_list
      post 'white_list', action: :update_white_list
    end
  end

  resources :templates, only: [:index]
  namespace :templates do
    resources :pushes, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :emails, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :system_messages, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :smses, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
  end

  resource :manual, controller: 'manual', only: [:show]
  namespace :manual do
    resources :system_messages, only: [:index, :create, :new]
    resources :emails, only: [:index, :create, :new] do
      collection do
        get 'good_items', to: 'emails#new_good_items'
        post 'good_items', to: 'emails#create_good_items'
      end
    end
    resources :statistics, only:[:index]
  end

  resources :user_feedback, only: [:index] do
    member do
      get 'feedback', action: :edit
      post 'feedback', action: :update
      get 'create_zendesk_ticket', action: :create_zendesk_ticket
    end
  end

  namespace :fmmc do
    resources :crons, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :tasks, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
    resources :triggers, except: [:destroy] do
      member do
        get 'enable'
        get 'disable'
      end
    end
  end

  namespace :tools do
    resources :items, only: [:index]
    resource :start_image, controller: 'start_image', only: [:edit, :update, :destroy]
    resource :home_banner, controller: 'home_banner', only: [:edit, :update, :destroy]
    resource :recommend_items, controller: 'recommend_items', only: [:create, :new]
  end

  namespace :tools do
    resources :items, only: [:index]
  end

  resource :api, controller: 'api', only: [] do
    collection do
      post 'country'
      post 'category'
    end
  end

  resources :item_tasks, only: [:index, :show, :create] do
    member do
      post 'complete', action: :complete
      post 'execute_action', action: :execute_action
    end
    collection do
      post 'create_and_execute', action: :create_and_execute
    end

    resources :item_task_comments
  end

  resources :item_operation_rules, only: [:index, :new, :create, :show, :edit, :update] do
    member do
      get 'enable', action: :enable
      get 'disable', action: :disable
    end
  end

  namespace :smart_audit do
    resources :operators, only: [:index, :update] do
      post 'check_in'
      post 'check_out'
    end

    resources :board, only: [:index] do

      post 'change_category'

      post 'assign_data'

      collection do
        post 'pass_images',action: :pass_images
        get 'stat_info'
        get 'list_images'
        get 'list_items'
        post 'approve'
        post 'item_task_execute'
        post 'set_first_image'
      end
    end

    resources :owners, only: [:index]
    resources :tasks, only: [:index] do
      post 'quick_task_exec', action: :quick_task_exec
      member do
        post 'refresh', action: :query_task_state
      end
      collection do
        get 'get_rules'
        get 'get_img_audit_rules'
        get 'get_often_use_rules'
        post 'ajax', action: :item_task_ajax
      end
    end
  end

  namespace :smart_ads do

    resources :board, only: [:index] do

      collection do
        get 'update_info'
        get 'list_items'

        post "clear_current_feeds", action: :clear_product_feed
        post "select_feeds", action: :add_product_feed
      end
    end

  end

  get "es/list" => "es#list"
  get "es" => "es#index"

  get "my_506/bkuser" => "test#bkuser"
  get "my_506/execa" => "test#execa"
  get "my_506/q" => "test#test_q"
  get "my_506/agents" => "test#test_agents"
  get "my_506/empls" =>"test#test_empls"
  get "my_506/ph" =>"test#test_ph"
  get "my_506/wl" =>"test#test_wl"

end

app/controllers/operator_schedules_controller.rb
class OperatorSchedulesController < ApplicationController
  before_action :get_schedule_params, only: [:create, :update]
  before_action :find_schedule, only: [:edit, :update]
  before_action :get_from_url, except: [:index]

  def index
    @schedules_grid = initialize_grid(BkOperatorSchedule,
                                      include: [:operator],
                                      order: 'bk_operator_schedules.id',
                                      order_direction: 'desc')
  end

  def new
    @schedule = BkOperatorSchedule.new
    @schedule.operator_id = params[:operator_id].to_i if params[:operator_id].present?
  end

  def create
    @schedule = BkOperatorSchedule.new(@schedule_params)
    if @schedule.save
      flash[:success] = "Create schedule successfully"
      redirect_to @from_url
    else
      flash[:error] = "Failed to create schedule"
      render 'new'
    end
  end

  def edit

  end

  def update
    if @schedule.update(@schedule_params)
      flash[:success] = "Update schedule successfully"
      redirect_to @from_url
    else
      flash[:error] = "Failed to update schedule"
      render 'edit'
    end
  end

  private

  def find_schedule
    @schedule = BkOperatorSchedule.find(params[:id])
  end

  def get_schedule_params
    schedule = params[:schedule]
    @schedule_params = {}
    @schedule_params['operator_id'] = schedule[:operator_id]
    @schedule_params['state'] = schedule[:state]
    start_time_array = []
    schedule.keys.sort.grep(/start_time/).each do |key|
      start_time_array << schedule[key]
    end
    end_time_array = []
    schedule.keys.sort.grep(/end_time/).each do |key|
      end_time_array << schedule[key]
    end
    @schedule_params['start_time'] = Time.zone.parse(Time.new(*start_time_array).to_s(:db))
    @schedule_params['end_time'] = Time.zone.parse(Time.new(*end_time_array).to_s(:db))
  end

  def get_from_url
    @from_url = params[:from_url]
  end

end

app/helpers/operator_schedules_helper.rb
module OperatorSchedulesHelper
end

app/views/operator_schedules/_form.html.erb
<%= form_for @schedule, as: 'schedule', url: local_url, html: {class: 'form-horizontal', role: 'form'} do |f| %>

    <% if @schedule.errors.any? %>
        <div class="alert alert-danger">
          <h3><%= pluralize(@schedule.errors.size, "error") %></h3>
          <ul>
            <% @schedule.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= hidden_field_tag :from_url, @from_url %>

    <div class="form-group">
      <%= f.label :operator, class: 'col-md-4 control-label' %>
      <div class="col-md-5">
        <% if @schedule.operator.blank? %>
            <%= f.select :operator_id, options_for_select(Admin.review_operators_for_select), {prompt: "Please select an operator"},
                         class: 'form-control', required: true %>
        <% else %>
            <p class="form-control"><%= @schedule.operator.username %></p>
            <%= f.hidden_field :operator_id %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :start_time, class: 'col-md-4 control-label' %>
      <div class="col-md-5">
        <%= f.datetime_select :start_time, {}, class: 'datetime-select', required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :end_time, class: 'col-md-4 control-label' %>
      <div class="col-md-5">
        <%= f.datetime_select :end_time, {}, class: 'datetime-select', required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :state, class: 'col-md-4 control-label' %>
      <div class="col-md-5">
        <%= f.select :state, options_for_select(Settings.BACKEND_USER.ScheduleStates, @schedule.state),
                     {prompt: 'Please select a state'},
                     class: 'form-control', required: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-5 col-md-5">
        <%= f.submit class: "btn btn-md btn-primary" %>
        <%= link_to 'Cancel', :back, class: "btn btn-md btn-default" %>
      </div>
    </div>

<% end %>

app/views/operator_schedules/edit.html.erb
<h2>Update Schedule</h2>

<hr/>

<%= render partial: 'form', locals: {local_url: schedule_path(@schedule)} %>

app/views/operator_schedules/index.html.erb
<h2> Schedule List </h2>

<div class="col-md-10">
  <hr/>
  <div class="btn-toolbar" role="toolbar">
    <div class="btn-group pull-right">
      <%= link_to "Create", new_schedule_path(from_url: schedules_path), class: "btn btn-md btn-primary" %>
    </div>
  </div>

  <%= grid(@schedules_grid) do |g|

    g.column name: "ID", attribute: 'id', html: {class: 'col-md-1'}

    g.column name: "Username", model: 'Admin', attribute: 'username', html: {class: 'col-md-2'} do |task|
      link_to task.operator.username, admin_path(task.operator)
    end

    g.column name: "StartTime", attribute: 'start_time', html: {class: 'col-md-3'}

    g.column name: 'EndTime', attribute: 'end_time', html: {class: 'col-md-3'}

    g.column name: 'State', attribute: 'state', html: {class: 'col-md-1'} do |task|
      Settings.BACKEND_USER.ScheduleStates.invert[task.state]
    end

    g.column do |task|
      link_to 'Edit', edit_schedule_path(task, from_url: schedules_path), class: 'btn btn-danger'
    end

  end -%>
</div>

app/views/operator_schedules/new.html.erb
<h2>Create Schedule</h2>

<hr/>

<%= render partial: 'form', locals: {local_url: schedules_path(@schedule)} %>